FROM --platform=linux/arm64/v8 ubuntu

# Avoid command line prompts
ENV TZ=Europe/Berlin
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install -y sudo

RUN adduser --disabled-password --gecos '' kafka \
    && adduser kafka sudo \
    && echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

USER kafka

WORKDIR /home/kafka

RUN sudo apt update && \
    sudo apt install -y \
        curl \
        zip \
        unzip \
        java-common \
    && sudo rm -rf /var/lib/apt/lists/*

# Install kafka
# https://kafka.apache.org/downloads
RUN curl -LO "https://dlcdn.apache.org/kafka/3.1.0/kafka_2.13-3.1.0.tgz" \
    && tar -xzf kafka_2.13-3.1.0.tgz \
    && rm kafka_2.13-3.1.0.tgz

RUN mv kafka_2.13-3.1.0 kafka

# Install sdkman, java and scala:
SHELL ["/bin/bash", "-c"]
RUN curl -s "https://get.sdkman.io" | bash 
RUN source .sdkman/bin/sdkman-init.sh; sdk install scala; sdk install java 18-amzn
ENTRYPOINT bash -c "source $HOME/.sdkman/bin/sdkman-init.sh && $0 $@" 

CMD ["bash"]
